//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Faslink.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietNghiPhep
    {
        public int IdChiTietNghiPhep { get; set; }
        public Nullable<System.DateTime> TuNgay { get; set; }
        public Nullable<System.TimeSpan> TuGio { get; set; }
        public Nullable<System.DateTime> DenNgay { get; set; }
        public Nullable<System.TimeSpan> DenGio { get; set; }
        public int IdNghiPhep { get; set; }
        public int IdNhanVien { get; set; }
        public int IdLoaiPhep { get; set; }
    
        public virtual NghiPhep NghiPhep { get; set; }
    }
}
