//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Faslink.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CongTac
    {
        public int IdCongTac { get; set; }
        public int IdNhanVien { get; set; }
        public string ChiNhanh { get; set; }
        public string DiaDiem_CongTac { get; set; }
        public Nullable<System.DateTime> TuNgay { get; set; }
        public Nullable<System.DateTime> DenNgay { get; set; }
        public Nullable<double> SoNgay_CongTac { get; set; }
        public string NguoiDuyet { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.DateTime> NgaySua { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
