//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Faslink.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonNghiPhep
    {
        public int ID_DonNghiPhep { get; set; }
        public string Hoten { get; set; }
        public string ChucVu { get; set; }
        public string BoPhan { get; set; }
        public Nullable<double> SoNgayNghi { get; set; }
        public Nullable<System.DateTime> GioBatDau { get; set; }
        public Nullable<System.DateTime> GioKetThuc { get; set; }
        public string LyDo { get; set; }
        public string NguoiBanGiao { get; set; }
        public string CongViecBanGiao { get; set; }
        public Nullable<System.DateTime> TuNgay { get; set; }
        public Nullable<System.DateTime> DenNgay { get; set; }
    }
}
