//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Faslink.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonXinNghiThaiSan
    {
        public int IdDonXinNghiThaiSan { get; set; }
        public int IdNhanVien { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<System.DateTime> ThoiGianKetThuc { get; set; }
        public Nullable<System.TimeSpan> TuGio { get; set; }
        public Nullable<System.TimeSpan> ToiGio { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
