//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Faslink.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class HopDongLaoDong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HopDongLaoDong()
        {
            this.LogHDLD = new HashSet<LogHDLD>();
            this.TinhTrangHopDong = new HashSet<TinhTrangHopDong>();
        }
    
        public int IdHopDong { get; set; }
        public int IdNhanVien { get; set; }
        public int IdLoaiHopDong { get; set; }
        public string SoHopDong { get; set; }
        public Nullable<System.DateTime> NgayKy { get; set; }
        public string BoPhan { get; set; }
        public string NgheNghiep { get; set; }
        public string ChucDanh { get; set; }
        public string DiaDiemLamViec { get; set; }
        public Nullable<decimal> Luong { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string NguoiTao { get; set; }
        public Nullable<System.DateTime> NgayThanhLy { get; set; }
        public Nullable<System.DateTime> TuNgay { get; set; }
        public Nullable<System.DateTime> DenNgay { get; set; }
    
        public virtual LoaiHopDong LoaiHopDong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogHDLD> LogHDLD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TinhTrangHopDong> TinhTrangHopDong { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
