//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Faslink.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhamThaiSan
    {
        public int IdKhamThaiSan { get; set; }
        public Nullable<int> Thang { get; set; }
        public Nullable<int> Tuan { get; set; }
        public Nullable<int> Ngay { get; set; }
        public string NoiDung { get; set; }
        public int IdThaiSan { get; set; }
        public int IdNhanVien { get; set; }
    
        public virtual ThaiSan ThaiSan { get; set; }
    }
}
