//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Faslink.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichLamViec
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LichLamViec()
        {
            this.LichNhanVien = new HashSet<LichNhanVien>();
        }
    
        public int IdLich { get; set; }
        public string TenLich { get; set; }
        public Nullable<System.TimeSpan> Thu2 { get; set; }
        public Nullable<System.TimeSpan> Thu3 { get; set; }
        public Nullable<System.TimeSpan> Thu4 { get; set; }
        public Nullable<System.TimeSpan> Thu5 { get; set; }
        public Nullable<System.TimeSpan> Thu6 { get; set; }
        public Nullable<System.TimeSpan> Thu7 { get; set; }
        public Nullable<System.TimeSpan> ChuNhat { get; set; }
        public string Ka { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichNhanVien> LichNhanVien { get; set; }
    }
}
