//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Faslink.Models.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class FaslinkEntities : DbContext
    {
        public FaslinkEntities()
            : base("name=FaslinkEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BHXHBHYT> BHXHBHYT { get; set; }
        public virtual DbSet<CongNhanMoi> CongNhanMoi { get; set; }
        public virtual DbSet<CongTac> CongTac { get; set; }
        public virtual DbSet<ChiTietNghiPhep> ChiTietNghiPhep { get; set; }
        public virtual DbSet<ChucVu> ChucVu { get; set; }
        public virtual DbSet<ChuyenCan> ChuyenCan { get; set; }
        public virtual DbSet<ChuyenCongTac> ChuyenCongTac { get; set; }
        public virtual DbSet<DiaChiLienLac> DiaChiLienLac { get; set; }
        public virtual DbSet<DiaChiThuongTru> DiaChiThuongTru { get; set; }
        public virtual DbSet<DiaDiemLamViec> DiaDiemLamViec { get; set; }
        public virtual DbSet<DonNghiPhep> DonNghiPhep { get; set; }
        public virtual DbSet<DonXinNghiThaiSan> DonXinNghiThaiSan { get; set; }
        public virtual DbSet<HopDongLaoDong> HopDongLaoDong { get; set; }
        public virtual DbSet<KhamThaiSan> KhamThaiSan { get; set; }
        public virtual DbSet<LichLamViec> LichLamViec { get; set; }
        public virtual DbSet<LichNhanVien> LichNhanVien { get; set; }
        public virtual DbSet<LoaiHopDong> LoaiHopDong { get; set; }
        public virtual DbSet<LoaiPhep> LoaiPhep { get; set; }
        public virtual DbSet<LogBoPhan> LogBoPhan { get; set; }
        public virtual DbSet<LogHDLD> LogHDLD { get; set; }
        public virtual DbSet<NuoiConNho> NuoiConNho { get; set; }
        public virtual DbSet<NghiPhep> NghiPhep { get; set; }
        public virtual DbSet<NhanVien> NhanVien { get; set; }
        public virtual DbSet<NhanVienChucVu> NhanVienChucVu { get; set; }
        public virtual DbSet<Quan> Quan { get; set; }
        public virtual DbSet<Tinh> Tinh { get; set; }
        public virtual DbSet<TinhTrangHopDong> TinhTrangHopDong { get; set; }
        public virtual DbSet<ThaiSan> ThaiSan { get; set; }
        public virtual DbSet<ThuongPhat> ThuongPhat { get; set; }
        public virtual DbSet<TrinhDo> TrinhDo { get; set; }
    
        public virtual ObjectResult<ChiTietNhanVienTheoId_Result> ChiTietNhanVienTheoId(Nullable<int> idNhanVien)
        {
            var idNhanVienParameter = idNhanVien.HasValue ?
                new ObjectParameter("IdNhanVien", idNhanVien) :
                new ObjectParameter("IdNhanVien", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ChiTietNhanVienTheoId_Result>("ChiTietNhanVienTheoId", idNhanVienParameter);
        }
    
        public virtual ObjectResult<DanhSachNhanVien_Result> DanhSachNhanVien()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DanhSachNhanVien_Result>("DanhSachNhanVien");
        }
    
        public virtual int SuaNhanVien(Nullable<int> idNhanVien, string hoTen, Nullable<int> gioiTinh, Nullable<System.DateTime> ngayVao, Nullable<System.DateTime> ngaySinh, string noiSinh, string honNhan, string dienThoai, string dienThoaiNguoiThan, string emailCTy, string emailCaNhan, string quocTich, string tonGiao, string danToc, string hinh, Nullable<int> soNguoiPhuThuoc, Nullable<bool> trangThai, Nullable<int> mvt, string ka, string to, Nullable<System.DateTime> ngayNghi, string nguoiGioiThieu, string soCMND, Nullable<System.DateTime> ngayCap, string noiCap, string nguyenQuan)
        {
            var idNhanVienParameter = idNhanVien.HasValue ?
                new ObjectParameter("IdNhanVien", idNhanVien) :
                new ObjectParameter("IdNhanVien", typeof(int));
    
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("HoTen", hoTen) :
                new ObjectParameter("HoTen", typeof(string));
    
            var gioiTinhParameter = gioiTinh.HasValue ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(int));
    
            var ngayVaoParameter = ngayVao.HasValue ?
                new ObjectParameter("NgayVao", ngayVao) :
                new ObjectParameter("NgayVao", typeof(System.DateTime));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            var noiSinhParameter = noiSinh != null ?
                new ObjectParameter("NoiSinh", noiSinh) :
                new ObjectParameter("NoiSinh", typeof(string));
    
            var honNhanParameter = honNhan != null ?
                new ObjectParameter("HonNhan", honNhan) :
                new ObjectParameter("HonNhan", typeof(string));
    
            var dienThoaiParameter = dienThoai != null ?
                new ObjectParameter("DienThoai", dienThoai) :
                new ObjectParameter("DienThoai", typeof(string));
    
            var dienThoaiNguoiThanParameter = dienThoaiNguoiThan != null ?
                new ObjectParameter("DienThoaiNguoiThan", dienThoaiNguoiThan) :
                new ObjectParameter("DienThoaiNguoiThan", typeof(string));
    
            var emailCTyParameter = emailCTy != null ?
                new ObjectParameter("EmailCTy", emailCTy) :
                new ObjectParameter("EmailCTy", typeof(string));
    
            var emailCaNhanParameter = emailCaNhan != null ?
                new ObjectParameter("EmailCaNhan", emailCaNhan) :
                new ObjectParameter("EmailCaNhan", typeof(string));
    
            var quocTichParameter = quocTich != null ?
                new ObjectParameter("QuocTich", quocTich) :
                new ObjectParameter("QuocTich", typeof(string));
    
            var tonGiaoParameter = tonGiao != null ?
                new ObjectParameter("TonGiao", tonGiao) :
                new ObjectParameter("TonGiao", typeof(string));
    
            var danTocParameter = danToc != null ?
                new ObjectParameter("DanToc", danToc) :
                new ObjectParameter("DanToc", typeof(string));
    
            var hinhParameter = hinh != null ?
                new ObjectParameter("Hinh", hinh) :
                new ObjectParameter("Hinh", typeof(string));
    
            var soNguoiPhuThuocParameter = soNguoiPhuThuoc.HasValue ?
                new ObjectParameter("SoNguoiPhuThuoc", soNguoiPhuThuoc) :
                new ObjectParameter("SoNguoiPhuThuoc", typeof(int));
    
            var trangThaiParameter = trangThai.HasValue ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(bool));
    
            var mvtParameter = mvt.HasValue ?
                new ObjectParameter("Mvt", mvt) :
                new ObjectParameter("Mvt", typeof(int));
    
            var kaParameter = ka != null ?
                new ObjectParameter("Ka", ka) :
                new ObjectParameter("Ka", typeof(string));
    
            var toParameter = to != null ?
                new ObjectParameter("To", to) :
                new ObjectParameter("To", typeof(string));
    
            var ngayNghiParameter = ngayNghi.HasValue ?
                new ObjectParameter("NgayNghi", ngayNghi) :
                new ObjectParameter("NgayNghi", typeof(System.DateTime));
    
            var nguoiGioiThieuParameter = nguoiGioiThieu != null ?
                new ObjectParameter("NguoiGioiThieu", nguoiGioiThieu) :
                new ObjectParameter("NguoiGioiThieu", typeof(string));
    
            var soCMNDParameter = soCMND != null ?
                new ObjectParameter("SoCMND", soCMND) :
                new ObjectParameter("SoCMND", typeof(string));
    
            var ngayCapParameter = ngayCap.HasValue ?
                new ObjectParameter("NgayCap", ngayCap) :
                new ObjectParameter("NgayCap", typeof(System.DateTime));
    
            var noiCapParameter = noiCap != null ?
                new ObjectParameter("NoiCap", noiCap) :
                new ObjectParameter("NoiCap", typeof(string));
    
            var nguyenQuanParameter = nguyenQuan != null ?
                new ObjectParameter("NguyenQuan", nguyenQuan) :
                new ObjectParameter("NguyenQuan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SuaNhanVien", idNhanVienParameter, hoTenParameter, gioiTinhParameter, ngayVaoParameter, ngaySinhParameter, noiSinhParameter, honNhanParameter, dienThoaiParameter, dienThoaiNguoiThanParameter, emailCTyParameter, emailCaNhanParameter, quocTichParameter, tonGiaoParameter, danTocParameter, hinhParameter, soNguoiPhuThuocParameter, trangThaiParameter, mvtParameter, kaParameter, toParameter, ngayNghiParameter, nguoiGioiThieuParameter, soCMNDParameter, ngayCapParameter, noiCapParameter, nguyenQuanParameter);
        }
    
        public virtual int ThemBoPhan(string tenBoPhan)
        {
            var tenBoPhanParameter = tenBoPhan != null ?
                new ObjectParameter("TenBoPhan", tenBoPhan) :
                new ObjectParameter("TenBoPhan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThemBoPhan", tenBoPhanParameter);
        }
    
        public virtual ObjectResult<ThemDiaChiLienLac_Result> ThemDiaChiLienLac(string soNhaDuong, Nullable<System.DateTime> thoiGian, Nullable<bool> trangThai, Nullable<int> idTinh_TP, Nullable<int> idNhanVien, Nullable<int> idQuan_Huyen)
        {
            var soNhaDuongParameter = soNhaDuong != null ?
                new ObjectParameter("SoNhaDuong", soNhaDuong) :
                new ObjectParameter("SoNhaDuong", typeof(string));
    
            var thoiGianParameter = thoiGian.HasValue ?
                new ObjectParameter("ThoiGian", thoiGian) :
                new ObjectParameter("ThoiGian", typeof(System.DateTime));
    
            var trangThaiParameter = trangThai.HasValue ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(bool));
    
            var idTinh_TPParameter = idTinh_TP.HasValue ?
                new ObjectParameter("IdTinh_TP", idTinh_TP) :
                new ObjectParameter("IdTinh_TP", typeof(int));
    
            var idNhanVienParameter = idNhanVien.HasValue ?
                new ObjectParameter("IdNhanVien", idNhanVien) :
                new ObjectParameter("IdNhanVien", typeof(int));
    
            var idQuan_HuyenParameter = idQuan_Huyen.HasValue ?
                new ObjectParameter("IdQuan_Huyen", idQuan_Huyen) :
                new ObjectParameter("IdQuan_Huyen", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ThemDiaChiLienLac_Result>("ThemDiaChiLienLac", soNhaDuongParameter, thoiGianParameter, trangThaiParameter, idTinh_TPParameter, idNhanVienParameter, idQuan_HuyenParameter);
        }
    
        public virtual ObjectResult<ThemDiaChiThuongTru_Result> ThemDiaChiThuongTru(Nullable<int> idTinh_TP, string soNhaDuong, Nullable<bool> trangThai, Nullable<int> idNhanVien, Nullable<int> idQuan_Huyen)
        {
            var idTinh_TPParameter = idTinh_TP.HasValue ?
                new ObjectParameter("IdTinh_TP", idTinh_TP) :
                new ObjectParameter("IdTinh_TP", typeof(int));
    
            var soNhaDuongParameter = soNhaDuong != null ?
                new ObjectParameter("SoNhaDuong", soNhaDuong) :
                new ObjectParameter("SoNhaDuong", typeof(string));
    
            var trangThaiParameter = trangThai.HasValue ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(bool));
    
            var idNhanVienParameter = idNhanVien.HasValue ?
                new ObjectParameter("IdNhanVien", idNhanVien) :
                new ObjectParameter("IdNhanVien", typeof(int));
    
            var idQuan_HuyenParameter = idQuan_Huyen.HasValue ?
                new ObjectParameter("IdQuan_Huyen", idQuan_Huyen) :
                new ObjectParameter("IdQuan_Huyen", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ThemDiaChiThuongTru_Result>("ThemDiaChiThuongTru", idTinh_TPParameter, soNhaDuongParameter, trangThaiParameter, idNhanVienParameter, idQuan_HuyenParameter);
        }
    
        public virtual ObjectResult<ThemLogBoPhan_Result> ThemLogBoPhan(Nullable<System.DateTime> ngayThayDoi, Nullable<int> idNhanVien, Nullable<int> idBoPhan)
        {
            var ngayThayDoiParameter = ngayThayDoi.HasValue ?
                new ObjectParameter("NgayThayDoi", ngayThayDoi) :
                new ObjectParameter("NgayThayDoi", typeof(System.DateTime));
    
            var idNhanVienParameter = idNhanVien.HasValue ?
                new ObjectParameter("IdNhanVien", idNhanVien) :
                new ObjectParameter("IdNhanVien", typeof(int));
    
            var idBoPhanParameter = idBoPhan.HasValue ?
                new ObjectParameter("IdBoPhan", idBoPhan) :
                new ObjectParameter("IdBoPhan", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ThemLogBoPhan_Result>("ThemLogBoPhan", ngayThayDoiParameter, idNhanVienParameter, idBoPhanParameter);
        }
    
        public virtual ObjectResult<ThemNhanVien_Result> ThemNhanVien(Nullable<int> idNhanVien, string hoTen, Nullable<int> idGioiTinh, Nullable<System.DateTime> ngayVao, Nullable<System.DateTime> ngaySinh, string noiSinh, string honNhan, string dienThoai, string dienThoaiNguoiThan, string emailCTy, string emailCaNhan, string quocTich, string tonGiao, string danToc, string hinh, Nullable<int> soNguoiPhuThuoc, Nullable<bool> trangThai, Nullable<int> mvt, string ka, string toLamViec, Nullable<System.DateTime> ngayNghi, string nguoiGioiThieu, string soCMND, Nullable<System.DateTime> ngayCap, string noiCap, string nguyenQuan)
        {
            var idNhanVienParameter = idNhanVien.HasValue ?
                new ObjectParameter("IdNhanVien", idNhanVien) :
                new ObjectParameter("IdNhanVien", typeof(int));
    
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("HoTen", hoTen) :
                new ObjectParameter("HoTen", typeof(string));
    
            var idGioiTinhParameter = idGioiTinh.HasValue ?
                new ObjectParameter("IdGioiTinh", idGioiTinh) :
                new ObjectParameter("IdGioiTinh", typeof(int));
    
            var ngayVaoParameter = ngayVao.HasValue ?
                new ObjectParameter("NgayVao", ngayVao) :
                new ObjectParameter("NgayVao", typeof(System.DateTime));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            var noiSinhParameter = noiSinh != null ?
                new ObjectParameter("NoiSinh", noiSinh) :
                new ObjectParameter("NoiSinh", typeof(string));
    
            var honNhanParameter = honNhan != null ?
                new ObjectParameter("HonNhan", honNhan) :
                new ObjectParameter("HonNhan", typeof(string));
    
            var dienThoaiParameter = dienThoai != null ?
                new ObjectParameter("DienThoai", dienThoai) :
                new ObjectParameter("DienThoai", typeof(string));
    
            var dienThoaiNguoiThanParameter = dienThoaiNguoiThan != null ?
                new ObjectParameter("DienThoaiNguoiThan", dienThoaiNguoiThan) :
                new ObjectParameter("DienThoaiNguoiThan", typeof(string));
    
            var emailCTyParameter = emailCTy != null ?
                new ObjectParameter("EmailCTy", emailCTy) :
                new ObjectParameter("EmailCTy", typeof(string));
    
            var emailCaNhanParameter = emailCaNhan != null ?
                new ObjectParameter("EmailCaNhan", emailCaNhan) :
                new ObjectParameter("EmailCaNhan", typeof(string));
    
            var quocTichParameter = quocTich != null ?
                new ObjectParameter("QuocTich", quocTich) :
                new ObjectParameter("QuocTich", typeof(string));
    
            var tonGiaoParameter = tonGiao != null ?
                new ObjectParameter("TonGiao", tonGiao) :
                new ObjectParameter("TonGiao", typeof(string));
    
            var danTocParameter = danToc != null ?
                new ObjectParameter("DanToc", danToc) :
                new ObjectParameter("DanToc", typeof(string));
    
            var hinhParameter = hinh != null ?
                new ObjectParameter("Hinh", hinh) :
                new ObjectParameter("Hinh", typeof(string));
    
            var soNguoiPhuThuocParameter = soNguoiPhuThuoc.HasValue ?
                new ObjectParameter("SoNguoiPhuThuoc", soNguoiPhuThuoc) :
                new ObjectParameter("SoNguoiPhuThuoc", typeof(int));
    
            var trangThaiParameter = trangThai.HasValue ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(bool));
    
            var mvtParameter = mvt.HasValue ?
                new ObjectParameter("Mvt", mvt) :
                new ObjectParameter("Mvt", typeof(int));
    
            var kaParameter = ka != null ?
                new ObjectParameter("Ka", ka) :
                new ObjectParameter("Ka", typeof(string));
    
            var toLamViecParameter = toLamViec != null ?
                new ObjectParameter("ToLamViec", toLamViec) :
                new ObjectParameter("ToLamViec", typeof(string));
    
            var ngayNghiParameter = ngayNghi.HasValue ?
                new ObjectParameter("NgayNghi", ngayNghi) :
                new ObjectParameter("NgayNghi", typeof(System.DateTime));
    
            var nguoiGioiThieuParameter = nguoiGioiThieu != null ?
                new ObjectParameter("NguoiGioiThieu", nguoiGioiThieu) :
                new ObjectParameter("NguoiGioiThieu", typeof(string));
    
            var soCMNDParameter = soCMND != null ?
                new ObjectParameter("SoCMND", soCMND) :
                new ObjectParameter("SoCMND", typeof(string));
    
            var ngayCapParameter = ngayCap.HasValue ?
                new ObjectParameter("NgayCap", ngayCap) :
                new ObjectParameter("NgayCap", typeof(System.DateTime));
    
            var noiCapParameter = noiCap != null ?
                new ObjectParameter("NoiCap", noiCap) :
                new ObjectParameter("NoiCap", typeof(string));
    
            var nguyenQuanParameter = nguyenQuan != null ?
                new ObjectParameter("NguyenQuan", nguyenQuan) :
                new ObjectParameter("NguyenQuan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ThemNhanVien_Result>("ThemNhanVien", idNhanVienParameter, hoTenParameter, idGioiTinhParameter, ngayVaoParameter, ngaySinhParameter, noiSinhParameter, honNhanParameter, dienThoaiParameter, dienThoaiNguoiThanParameter, emailCTyParameter, emailCaNhanParameter, quocTichParameter, tonGiaoParameter, danTocParameter, hinhParameter, soNguoiPhuThuocParameter, trangThaiParameter, mvtParameter, kaParameter, toLamViecParameter, ngayNghiParameter, nguoiGioiThieuParameter, soCMNDParameter, ngayCapParameter, noiCapParameter, nguyenQuanParameter);
        }
    
        public virtual ObjectResult<ThemTrinhDo_Result> ThemTrinhDo(string hocVan, string truongHoc, string chuyenMon, string ngoaiNgu, string viTinh, Nullable<System.DateTime> thoiGian, Nullable<int> idNhanVien)
        {
            var hocVanParameter = hocVan != null ?
                new ObjectParameter("HocVan", hocVan) :
                new ObjectParameter("HocVan", typeof(string));
    
            var truongHocParameter = truongHoc != null ?
                new ObjectParameter("TruongHoc", truongHoc) :
                new ObjectParameter("TruongHoc", typeof(string));
    
            var chuyenMonParameter = chuyenMon != null ?
                new ObjectParameter("ChuyenMon", chuyenMon) :
                new ObjectParameter("ChuyenMon", typeof(string));
    
            var ngoaiNguParameter = ngoaiNgu != null ?
                new ObjectParameter("NgoaiNgu", ngoaiNgu) :
                new ObjectParameter("NgoaiNgu", typeof(string));
    
            var viTinhParameter = viTinh != null ?
                new ObjectParameter("ViTinh", viTinh) :
                new ObjectParameter("ViTinh", typeof(string));
    
            var thoiGianParameter = thoiGian.HasValue ?
                new ObjectParameter("ThoiGian", thoiGian) :
                new ObjectParameter("ThoiGian", typeof(System.DateTime));
    
            var idNhanVienParameter = idNhanVien.HasValue ?
                new ObjectParameter("IdNhanVien", idNhanVien) :
                new ObjectParameter("IdNhanVien", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ThemTrinhDo_Result>("ThemTrinhDo", hocVanParameter, truongHocParameter, chuyenMonParameter, ngoaiNguParameter, viTinhParameter, thoiGianParameter, idNhanVienParameter);
        }
    
        public virtual int XoaDiaChiLienLac(Nullable<int> idNhanVien)
        {
            var idNhanVienParameter = idNhanVien.HasValue ?
                new ObjectParameter("IdNhanVien", idNhanVien) :
                new ObjectParameter("IdNhanVien", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XoaDiaChiLienLac", idNhanVienParameter);
        }
    
        public virtual int XoaDiaChiThuongTru(Nullable<int> idNhanVien)
        {
            var idNhanVienParameter = idNhanVien.HasValue ?
                new ObjectParameter("IdNhanVien", idNhanVien) :
                new ObjectParameter("IdNhanVien", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XoaDiaChiThuongTru", idNhanVienParameter);
        }
    
        public virtual int XoaLogBoPhan(Nullable<int> idNhanVien)
        {
            var idNhanVienParameter = idNhanVien.HasValue ?
                new ObjectParameter("IdNhanVien", idNhanVien) :
                new ObjectParameter("IdNhanVien", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XoaLogBoPhan", idNhanVienParameter);
        }
    
        public virtual int XoaNhanVien(Nullable<int> idNhanVien)
        {
            var idNhanVienParameter = idNhanVien.HasValue ?
                new ObjectParameter("IdNhanVien", idNhanVien) :
                new ObjectParameter("IdNhanVien", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XoaNhanVien", idNhanVienParameter);
        }
    
        public virtual int XoaTrinhDo(Nullable<int> idNhanVien)
        {
            var idNhanVienParameter = idNhanVien.HasValue ?
                new ObjectParameter("IdNhanVien", idNhanVien) :
                new ObjectParameter("IdNhanVien", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XoaTrinhDo", idNhanVienParameter);
        }
    }
}
