//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Faslink.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class NghiPhep
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NghiPhep()
        {
            this.ChiTietNghiPhep = new HashSet<ChiTietNghiPhep>();
        }
    
        public int IdNghiPhep { get; set; }
        public string LyDo { get; set; }
        public Nullable<int> NguoiNhanBanGiaoId { get; set; }
        public string CongViecBanGiao { get; set; }
        public string NgayTao { get; set; }
        public string NguoiDuyet { get; set; }
        public int IdNhanVien { get; set; }
        public int IdLoaiPhep { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietNghiPhep> ChiTietNghiPhep { get; set; }
        public virtual LoaiPhep LoaiPhep { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
