//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Faslink.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class NuoiConNho
    {
        public int IdNuoiConNho { get; set; }
        public string HoTenCon { get; set; }
        public Nullable<System.DateTime> NgaySinhCon { get; set; }
        public Nullable<double> TuoiCon { get; set; }
        public int IdNhanVien { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
