//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Faslink.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThuongPhat
    {
        public int IdThuongPhat { get; set; }
        public Nullable<bool> ThuongPhat1 { get; set; }
        public string LyDo { get; set; }
        public Nullable<decimal> TienThuong { get; set; }
    }
}
