//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Faslink.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinhTrangHopDong
    {
        public int IdTinhTrangHD { get; set; }
        public string TenTinhTrang { get; set; }
        public int IdHopDong { get; set; }
        public int IdLoaiHopDong { get; set; }
        public int IdNhanVien { get; set; }
    
        public virtual HopDongLaoDong HopDongLaoDong { get; set; }
    }
}
